from django.shortcuts import render
from django.core.mail import send_mail
from django.contrib import messages
from .forms import ContactForm

def home(request):
    return render(request, 'common/home.html')


def about(request):
    return render(request, 'common/about.html')


def university(request):
    return render(request, 'common/university.html')


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            full_message = f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}"

            try:
                send_mail(
                    subject='Contact Form - Quiero Aprender',
                    message=full_message,
                    from_email=email,
                    recipient_list=['hb.hris.bal@gmail.com'],
                )
                messages.success(request, 'Your message was sent successfully!')
            except Exception as e:
                messages.error(request, f'There was a problem sending the message. Try again. {e}')

            return render(request, 'common/contact.html', {'form': ContactForm()})
    else:
        form = ContactForm()

    return render(request, 'common/contact.html', {'form': form})


def country_details(request, country_name):
    countries = {
        "argentina": {
            "name": "Argentina",
            "description": "Argentina is a large and diverse country in South America, bordered by Chile, Bolivia, Paraguay, Brazil, and Uruguay, with a long Atlantic coastline to the east. Known for its varied landscapes, Argentina boasts everything from the arid deserts of the north to the lush Pampas plains, and from the towering Andes mountains to the stunning glaciers of Patagonia in the south. The country has a strong cultural identity, heavily influenced by European, especially Italian and Spanish, immigrants. Buenos Aires, the vibrant capital, is known for its cosmopolitan feel, European-style architecture, and lively arts scene. It’s the birthplace of tango, the passionate dance and music that reflects Argentina’s soul, and the city is filled with tango clubs, theaters, and cafés. Argentina is also famous for its cuisine, particularly its world-renowned beef, often enjoyed asado-style (barbecued) in social gatherings. Wine from regions like Mendoza, especially Malbec, is another point of pride for Argentines and is highly regarded internationally. Natural attractions in Argentina are diverse and stunning. The Iguazu Falls, one of the world’s largest waterfall systems, lie in the tropical north, while the southern region of Patagonia offers awe-inspiring landscapes with glaciers, lakes, and rugged terrain ideal for trekking. The Valdes Peninsula on the Atlantic coast is a haven for wildlife, including penguins, sea lions, and whales. Sports, especially soccer, are a huge part of Argentine culture, and the country has produced legendary players like Diego Maradona and Lionel Messi. Known for its passionate spirit, rich traditions, and breathtaking landscapes, Argentina is a country that captivates visitors with its blend of natural beauty and cultural vibrancy.",
            "image": "images/countries/Argentina.jpg"
        },

        "bolivia": {
            "name": "Bolivia",
            "description": "Bolivia is a landlocked country in South America known for its breathtaking landscapes, rich Indigenous culture, and high-altitude cities. Bordered by Brazil, Paraguay, Argentina, Chile, and Peru, Bolivia is home to diverse ecosystems, from the Amazon rainforest to the Andes mountains and vast salt flats. La Paz, Bolivia's administrative capital, is one of the highest capital cities in the world, located at over 3,600 meters (11,800 feet) above sea level. Known for its dramatic setting among mountains, La Paz is a vibrant city with Indigenous markets, colonial architecture, and panoramic views from the Mi Teleférico cable car system. Sucre, the constitutional capital, is a UNESCO World Heritage Site and showcases well-preserved Spanish colonial buildings and a more relaxed atmosphere. One of Bolivia’s most famous natural attractions is Salar de Uyuni, the largest salt flat in the world. During the rainy season, it transforms into a giant mirror, creating surreal reflections that attract photographers and travelers worldwide. The country also boasts Lake Titicaca, the highest navigable lake in the world, shared with Peru and steeped in Indigenous myths. The islands on the lake, such as Isla del Sol, are dotted with ancient Inca ruins and offer a glimpse into the region’s spiritual heritage. Bolivia has one of the largest Indigenous populations in South America, primarily Aymara, Quechua, and Guaraní people, who maintain their languages, customs, and vibrant traditional clothing. The country's culture is rooted in Indigenous and Spanish influences, celebrated through festivals like Carnaval de Oruro, a UNESCO-recognized event featuring elaborate costumes, masks, and dances that blend Indigenous and Catholic traditions. Bolivian cuisine is hearty and diverse, reflecting Indigenous flavors and Spanish influences. Staples include corn, potatoes, and quinoa, which originated in the Andes. Popular dishes include salteñas (baked pastries filled with meat or vegetables), llajwa (a spicy sauce), and api (a warm, purple corn drink). In the highlands, llama and alpaca meat are commonly eaten, while fish dishes are popular near Lake Titicaca. Bolivia’s rugged landscapes and cultural depth make it a fascinating destination for those interested in exploring South America’s natural wonders and Indigenous heritage. With its rich history, high-altitude cities, and extraordinary geographic diversity, Bolivia offers a unique experience for travelers seeking adventure, culture, and authenticity.",
            "image": "images/countries/Bolivia.jpg"
        },

        "chile": {
            "name": "Chile",
            "description": "Chile is a long, narrow country stretching along the western edge of South America, bordered by Peru, Bolivia, Argentina, and the Pacific Ocean. Known for its strikingly diverse geography, Chile extends from the arid Atacama Desert in the north—one of the driest places on Earth—to the glaciers, fjords, and rugged peaks of Patagonia in the south. The country also encompasses the Andes mountains and a vast Pacific coastline, offering a wealth of natural beauty and outdoor activities. Santiago, the capital, is a modern, dynamic city nestled between the Andes and the coastal mountains, with a lively arts scene, historic neighborhoods, and vibrant food culture. Chile’s wine regions, particularly the Central Valley, are world-renowned for producing high-quality wines, especially reds like Cabernet Sauvignon and Carménère, which attract wine lovers from around the globe. Chile is culturally diverse, with influences from Indigenous groups like the Mapuche, as well as Spanish settlers. The traditional folk dance, the cueca, is celebrated nationwide, especially during the Fiestas Patrias, Chile’s independence celebrations. Another unique cultural highlight is Easter Island, a remote island in the Pacific Ocean, famous for its mysterious Moai statues and rich Polynesian heritage. Chilean cuisine is a mix of coastal and Andean flavors, with seafood playing a major role due to the country’s extensive coastline. Popular dishes include empanadas, pastel de choclo (a corn pie with meat and vegetables), and curanto, a traditional seafood and meat stew from the southern island of Chiloé. With its dramatic landscapes, rich culture, and warm people, Chile is a captivating country offering visitors everything from high-altitude deserts and pristine beaches to snowy mountains and lush forests. It’s a top destination for nature lovers, adventure seekers, and those interested in exploring a country that stretches across some of the most diverse ecosystems in the world.",
            "image": "images/countries/Chile.jpg"
        },

        "colombia": {
            "name": "Colombia",
            "description": "Colombia is a beautiful country in South America, bordered by Venezuela, Brazil, Peru, Ecuador, and Panama, with coastlines on both the Caribbean Sea and the Pacific Ocean. Known for its incredible biodiversity, Colombia has a vast range of landscapes, including the Andes mountains, the Amazon rainforest, coffee-growing highlands, and stunning beaches on the Caribbean coast. The country is rich in culture, blending Indigenous, African, and Spanish influences. Colombian music and dance, like cumbia and salsa, are vibrant expressions of this mix, and each region has its own unique traditions and flavors. Colombia is also famous for its coffee, considered some of the best in the world, grown in the lush Coffee Triangle region. Colombian cities offer a variety of experiences, from the modern, bustling capital of Bogotá, to Medellín’s innovative urban landscape, to the colonial charm of Cartagena with its colorful buildings and historical fortifications. Cali is renowned as the “salsa capital,” while Santa Marta offers access to the Tayrona National Natural Park, where mountains meet pristine beaches. Colombia’s warm, welcoming people, rich history, and natural wonders make it a fascinating destination for travelers interested in everything from outdoor adventures to cultural experiences. Despite challenges in its past, Colombia has transformed into a dynamic and friendly country, offering visitors a true taste of South American culture and natural beauty.",
            "image": "images/countries/Colombia.jpg"
        },

        "costa-rica": {
            "name": "Costa Rica",
            "description": "Costa Rica is a small but biodiverse country in Central America, bordered by Nicaragua to the north, Panama to the south, the Pacific Ocean to the west, and the Caribbean Sea to the east. Known for its commitment to environmental preservation, Costa Rica is a global leader in ecotourism and sustainability, making it a haven for nature lovers, adventurers, and those seeking relaxation in lush, tropical landscapes. San José, the capital, is the cultural and political center, with museums, theaters, and bustling markets that showcase Costa Rican art and history. However, the country's main draw is its incredible natural beauty. Costa Rica is home to a variety of ecosystems, including rainforests, cloud forests, volcanoes, beaches, and coral reefs. National parks and protected areas make up nearly a quarter of its territory, offering extensive opportunities for hiking, wildlife viewing, and adventure sports. Some of Costa Rica's most famous national parks include Manuel Antonio, known for its stunning beaches and wildlife; Arenal Volcano, which has hot springs and abundant trails; and Monteverde Cloud Forest Reserve, where visitors can explore misty, high-altitude rainforests teeming with rare plants and animals. The Osa Peninsula, home to Corcovado National Park, is one of the most biologically intense places on Earth, offering the chance to see species like scarlet macaws, jaguars, and tapirs. Costa Rican culture is a mix of Indigenous, Spanish, and Afro-Caribbean influences, especially evident in the Caribbean coastal regions. The local saying “pura vida” (meaning “pure life”) reflects the country’s relaxed, friendly lifestyle and approach to life. Costa Rica celebrates numerous festivals, with colorful parades, music, and dancing, and traditional music includes styles like cumbia, calypso, and folk tunes. The cuisine is simple and fresh, often featuring staples like rice, beans, plantains, and fresh fruits. Popular dishes include gallo pinto (rice and beans typically eaten for breakfast), casado (a traditional meal with rice, beans, salad, and a choice of meat), and ceviche. Fresh seafood is abundant on the coasts, and coffee, a major export, is considered some of the best in the world. Costa Rica's peaceful nature, friendly people, and commitment to sustainability make it a standout destination for those interested in ecotourism, adventure, and a deep appreciation for natural beauty. It’s a country where visitors can experience pristine rainforests, idyllic beaches, and the “pura vida” lifestyle in one of the world’s most ecologically diverse regions.",
            "image": "images/countries/Costa-Rica.jpg"
        },

        "cuba": {
            "name": "Cuba",
            "description": "Cuba is a culturally rich and historically significant island nation in the Caribbean, located south of Florida and east of Mexico's Yucatán Peninsula. Known for its colonial architecture, vintage cars, music, and vibrant culture, Cuba has a unique charm shaped by its history, politics, and diverse heritage. Havana, the capital, is famous for its lively atmosphere, with pastel-colored colonial buildings, historic plazas, and iconic 1950s American cars cruising its streets. The city is a UNESCO World Heritage Site, and places like the Malecón (a waterfront promenade), Plaza de la Revolución, and El Capitolio showcase its cultural and historical depth. Havana is also known for its vibrant nightlife, with salsa music, jazz, and Afro-Cuban rhythms filling the air. Cuban culture blends Spanish, African, and Indigenous influences, which are reflected in its music, dance, and art. Music is central to Cuban life, with genres like son, rumba, and salsa originating from Cuba. The Buena Vista Social Club and artists like Celia Cruz and Benny Moré helped popularize Cuban music worldwide. Cuban cuisine, known as comida criolla, combines Spanish, African, and Caribbean flavors. Traditional dishes include ropa vieja (shredded beef in tomato sauce), moros y cristianos (black beans and rice), and yuca con mojo (cassava with garlic sauce). Rum, a national product, is the base for classic Cuban cocktails like the mojito and daiquiri. Outside of the cities, Cuba offers beautiful natural landscapes. The Viñales Valley, with its limestone hills and tobacco fields, is ideal for hiking and exploring rural Cuban life. Cuba’s beaches, such as Varadero and Cayo Coco, are famous for their clear waters and white sands. The island also has protected natural areas, like the Zapata Swamp, which is home to diverse wildlife. Despite economic challenges, Cuba remains a country of warmth, resilience, and strong cultural pride. Its rich history, passionate spirit, and unique way of life make it a fascinating destination for travelers interested in exploring a mix of history, natural beauty, and vibrant local culture.",
            "image": "images/countries/Cuba.jpg"
        },

        "dominican-republic": {
            "name": "Dominican Republic",
            "description": "The Dominican Republic, located on the eastern part of the Caribbean island of Hispaniola (which it shares with Haiti), is known for its beautiful beaches, rich culture, and lively atmosphere. Bordered by the Atlantic Ocean to the north and the Caribbean Sea to the south, the country offers a diverse landscape of tropical forests, mountain ranges, fertile valleys, and coastal resorts. Santo Domingo, the capital, is the oldest European city in the Americas and boasts a well-preserved colonial district, known as the Zona Colonial, a UNESCO World Heritage Site. This historic area features cobblestone streets, colorful buildings, and landmarks like the first cathedral and the Alcázar de Colón, which provide a window into the country's colonial past. Santo Domingo is also a modern, bustling city with vibrant nightlife, arts, and culinary scenes. The Dominican Republic is famous for its beaches, particularly in Punta Cana, Puerto Plata, and Samaná, where visitors can enjoy white sands, crystal-clear waters, and a wide range of resorts. The country's natural beauty extends beyond the coast; it’s home to Pico Duarte, the highest peak in the Caribbean, and unique sites like Lake Enriquillo, a saltwater lake inhabited by American crocodiles and flamingos. Dominican culture is a lively blend of African, Spanish, and Indigenous Taino influences. Music and dance are at the heart of Dominican life, with merengue and bachata being the country’s signature genres. Festivals, like Carnival, bring the streets alive with colorful costumes, music, and dance, celebrating the country’s history and spirit. Dominican cuisine, known as comida criolla, is flavorful and influenced by local ingredients. Popular dishes include mangu (mashed plantains), sancocho (a hearty meat and vegetable stew), and arroz con habichuelas (rice and beans). Fresh seafood and tropical fruits like mango, papaya, and passionfruit are widely enjoyed. Known for its warm and welcoming people, the Dominican Republic embraces the phrase “República Dominicana lo tiene todo” (the Dominican Republic has it all). From stunning beaches and historic sites to lively culture and natural wonders, the Dominican Republic is a top Caribbean destination that offers both relaxation and adventure for travelers.",
            "image": "images/countries/Dominican-Republic.jpg"
        },

        "ecuador": {
            "name": "Ecuador",
            "description": "Ecuador is a small but diverse country on the western coast of South America, bordered by Colombia, Peru, and the Pacific Ocean. Named after the equator that runs through it, Ecuador offers a remarkable variety of landscapes, from the Amazon rainforest and Andean highlands to stunning Pacific beaches and the famed Galápagos Islands. Quito, the capital, is located high in the Andes and is known for its well-preserved colonial architecture and vibrant cultural heritage. As a UNESCO World Heritage Site, Quito’s historic center features cobblestone streets, grand churches, and beautiful plazas. Guayaquil, the country’s largest city and main port, has a lively waterfront and serves as a gateway to the Galápagos Islands. Ecuador is renowned for its biodiversity, especially in the Galápagos Islands, which are home to unique wildlife like giant tortoises, marine iguanas, and blue-footed boobies. These islands inspired Charles Darwin’s theory of evolution and remain a popular destination for ecotourism. The Amazon region of Ecuador, known as the Oriente, also draws nature enthusiasts with its rich rainforest ecosystem, rivers, and Indigenous communities. Ecuadorian culture reflects a blend of Indigenous, Spanish, and Afro-Ecuadorian influences. Traditional music and dance, like the highland sanjuanito and Afro-Ecuadorian marimba, are vibrant parts of Ecuadorian life. The country's cuisine is diverse, featuring dishes like ceviche on the coast, roasted guinea pig (or cuy) in the Andes, and tropical fruits from the Amazon. In addition to its natural beauty and cultural richness, Ecuador’s compact size makes it easy for visitors to experience its varied regions. The country is also notable for using the U.S. dollar as its official currency, making it accessible for many travelers. Ecuador’s mix of stunning landscapes, unique wildlife, and warm hospitality make it an extraordinary destination for those interested in nature, adventure, and cultural exploration.",
            "image": "images/countries/Ecuador.jpg"
        },

        "el-salvador": {
            "name": "El Salvador",
            "description": "El Salvador, the smallest country in Central America, is known for its stunning Pacific coastline, volcanic landscapes, and rich cultural heritage. Bordered by Honduras, Guatemala, and the Pacific Ocean, this compact country is often called the 'Land of Volcanoes' due to its many active and dormant volcanoes that shape its dramatic terrain. San Salvador, the capital, is a bustling city with a mix of modernity and history, featuring landmarks like the Metropolitan Cathedral, National Palace, and lively public squares. The city offers museums, cultural centers, and an emerging culinary scene, while nearby volcanoes like the San Salvador Volcano provide outdoor adventure opportunities right outside the urban landscape. El Salvador’s Pacific coast is famous for its world-class surf spots, especially in areas like El Tunco and La Libertad. Surfers and beach lovers are drawn to these beaches for the strong waves, scenic shores, and laid-back atmosphere. Inland, natural attractions like Cerro Verde National Park, with views of the Izalco and Santa Ana volcanoes, offer beautiful hiking trails and spectacular vistas. The country's culture is influenced by Indigenous heritage and Spanish colonial history. Traditional arts and crafts, such as colorful textiles and pottery, reflect this blend. Festivals are an essential part of life in El Salvador, with events like Las Bolas de Fuego (Balls of Fire Festival) in Nejapa and Semana Santa (Holy Week) celebrated with great enthusiasm. Salvadoran cuisine features hearty, flavorful dishes with Indigenous and Spanish influences. Pupusas, thick corn tortillas filled with cheese, beans, or meat, are the national dish and beloved across the country. Other popular foods include yuca frita (fried cassava) and sopa de pata (a hearty soup with cow’s feet and vegetables). Despite its small size, El Salvador offers a mix of natural beauty, vibrant culture, and friendly locals, making it a hidden gem for travelers seeking authentic Central American experiences. With its warm climate, scenic landscapes, and rich traditions, it’s an ideal destination for those interested in both outdoor adventure and cultural exploration.",
            "image": "images/countries/El-Salvador.jpg"
        },

        "equatorial-guinea": {
            "name": "Equatorial Guinea",
            "description": "Equatorial Guinea is a small country on the west coast of Central Africa, known for its unique blend of African and Spanish influences, lush tropical landscapes, and rich biodiversity. It is one of the few African countries where Spanish is an official language, reflecting its colonial history under Spain. The country consists of a mainland region, known as Río Muni, and several islands, with Bioko Island being the most significant. Malabo, the capital, is located on Bioko Island and is characterized by its colonial architecture, colorful markets, and vibrant Afro-Iberian culture. The mainland region of Río Muni is covered by dense rainforests, rivers, and mountains, offering habitats for a wide array of wildlife, including gorillas, elephants, and numerous bird species. The Monte Alén National Park is a popular spot for ecotourism, where visitors can explore diverse ecosystems and experience the country’s unspoiled natural beauty. Equatorial Guinea’s cultural life reflects a fusion of Indigenous customs and Spanish heritage. Traditional music and dance play an important role, especially during festivals and celebrations. Fang and Bubi are two prominent ethnic groups in Equatorial Guinea, each with its own traditions and languages. The country also celebrates Spanish and Catholic holidays alongside local festivities. The cuisine of Equatorial Guinea includes a variety of local and imported flavors. Staple foods include cassava, yams, plantains, and rice, often served with fish, chicken, or goat. Spanish influence is evident in dishes like tortilla española (Spanish omelet) and paella. Fresh seafood is abundant, and tropical fruits such as bananas, pineapples, and mangoes are commonly enjoyed. Equatorial Guinea is one of Africa’s largest oil producers, which has driven recent economic growth, though income inequality remains a significant issue. Despite its small size, Equatorial Guinea offers travelers a fascinating blend of cultural heritage, natural beauty, and tropical biodiversity, making it a unique destination in Central Africa.",
            "image": "images/countries/Equatorial-Guinea.jpg"
        },

        "guatemala": {
            "name": "Guatemala",
            "description": "Guatemala is a beautiful and culturally rich country in Central America, bordered by Mexico, Belize, Honduras, El Salvador, and the Pacific Ocean to the west. Known for its stunning landscapes, ancient Mayan ruins, and vibrant Indigenous culture, Guatemala offers visitors a unique mix of history, nature, and traditional ways of life. Guatemala City, the capital, is a bustling urban center with museums, historic sites, and markets, but many travelers are drawn to nearby Antigua. Antigua is a colonial town surrounded by volcanoes and known for its well-preserved Spanish Baroque architecture and cobblestone streets. It's also a UNESCO World Heritage Site, and its lively markets, colorful festivals, and coffee culture attract many visitors. The country’s rich Indigenous heritage is evident in places like Lake Atitlán, a stunning highland lake surrounded by volcanoes and traditional villages. The local Maya people maintain their languages, dress, and customs, and each village around the lake has its own distinct identity. The Maya culture is deeply rooted in Guatemala, and the country is home to Tikal, one of the largest and most impressive ancient Mayan cities. Set deep in the jungle, Tikal features towering temples and structures that offer a glimpse into one of the most advanced pre-Columbian civilizations. Guatemalan cuisine reflects Mayan and Spanish influences, with dishes like pepian (a spicy meat stew), tamales, and kak'ik (a traditional turkey soup). Corn, beans, and chiles are staples in the diet, and Guatemalan coffee is highly regarded worldwide. Guatemala’s landscapes range from dense rainforests and active volcanoes to beautiful beaches on both the Pacific and Caribbean coasts. The country’s biodiversity and natural beauty make it ideal for ecotourism, with opportunities for hiking, birdwatching, and exploring lush forests. Despite challenges, Guatemala is known for its warm hospitality, rich traditions, and strong cultural pride. For travelers, it offers a blend of breathtaking landscapes, ancient history, and a deeply rooted Indigenous culture that creates an unforgettable experience.",
            "image": "images/countries/Guatemala.jpg"
        },

        "honduras": {
            "name": "Honduras",
            "description": "Honduras is a Central American country known for its natural beauty, ancient Mayan history, and diverse ecosystems. Bordered by Guatemala, El Salvador, Nicaragua, and both the Caribbean Sea and the Pacific Ocean, Honduras is rich in culture and geography, offering everything from lush rainforests and mountain ranges to tropical islands and coral reefs. Tegucigalpa, the capital, is a vibrant city with a mix of colonial architecture, bustling markets, and modern developments. Another important city is San Pedro Sula, known for its business and commercial activity. Many visitors, however, are drawn to the Caribbean coast and the Bay Islands, a group of tropical islands famous for their white-sand beaches and exceptional diving sites. Roatán, Utila, and Guanaja are particularly popular for diving and snorkeling due to the Mesoamerican Barrier Reef, the second-largest coral reef system in the world. Honduras is home to Copán, one of the most significant ancient Mayan sites. Located in the western part of the country, Copán features intricately carved stelae, altars, and pyramids, offering a fascinating glimpse into Mayan history and artistry. The site is a UNESCO World Heritage Site and is known for its detailed hieroglyphics and well-preserved structures. The country's landscapes are diverse, from cloud forests in La Tigra National Park to tropical rainforests in the Río Plátano Biosphere Reserve. Honduras is rich in biodiversity, with opportunities for ecotourism, birdwatching, and hiking. Its natural reserves protect unique wildlife and plant species, including jaguars, howler monkeys, and colorful bird species like the scarlet macaw, Honduras's national bird. Honduran cuisine is a blend of Indigenous, African, and Spanish influences. Typical dishes include baleadas (flour tortillas filled with beans, cheese, and sometimes meat), tamales, and sopa de caracol (conch soup), reflecting the coastal regions' flavors. Fresh seafood is abundant, especially on the Caribbean coast, where coconut-infused dishes are common. Honduras is a country of contrasts, combining ancient history, modern cities, and untouched natural beauty. Its warm, welcoming people and scenic landscapes make it an inviting destination for those interested in both cultural exploration and outdoor adventure.",
            "image": "images/countries/Honduras.jpg"
        },

        "mexico": {
            "name": "Mexico",
            "description": "Mexico is a vibrant country located in North America, bordered by the United States to the north, the Pacific Ocean to the west, the Gulf of Mexico to the east, and Central America to the south. Known for its rich history, Mexico is home to ancient civilizations like the Maya and the Aztecs, with impressive ruins like Chichen Itza and Teotihuacan still standing as reminders of its past. The country's culture is a colorful blend of indigenous traditions and Spanish influences, evident in its cuisine, music, festivals, and art. Mexican cuisine is world-famous for dishes like tacos, enchiladas, and mole, along with the iconic drinks tequila and mezcal. Mexico’s geography is diverse, featuring stunning beaches along the Caribbean coast, deserts in the north, lush jungles in the south, and mountains and volcanoes throughout the central region. Cities like Mexico City, Guadalajara, and Monterrey offer modern, urban experiences, while places like Cancún and Tulum are popular for their beautiful coastal scenery and vibrant tourism. Mexico also celebrates many unique festivals, such as Día de los Muertos (Day of the Dead), where people honor deceased loved ones with colorful altars, food, and parades. The country’s warm climate, welcoming people, and diverse landscapes make it a popular destination for travelers around the world.",
            "image": "images/countries/Mexico.jpg"
        },

        "nicaragua": {
            "name": "Nicaragua",
            "description": "Nicaragua is a picturesque and culturally rich country in Central America, bordered by Honduras to the north, Costa Rica to the south, the Pacific Ocean to the west, and the Caribbean Sea to the east. Known as the 'Land of Lakes and Volcanoes,' Nicaragua offers a diverse landscape of volcanoes, vast lakes, tropical rainforests, and pristine beaches. Managua, the capital, is Nicaragua's largest city and a major cultural and economic center, with vibrant markets, historical sites, and a growing arts scene. However, much of Nicaragua’s charm is found in its colonial towns, especially Granada and León. Granada, located on the shores of Lake Nicaragua, is famous for its well-preserved Spanish colonial architecture, colorful buildings, and nearby islands known as (Las Isletas.) León, a university town, is known for its political history, artistic spirit, and beautiful cathedrals. Nicaragua’s natural beauty is one of its main attractions. Lake Nicaragua, the largest lake in Central America, is home to Ometepe Island, which features twin volcanoes and is a popular spot for hiking and ecotourism. The Pacific coast offers scenic beaches, particularly in places like San Juan del Sur, a laid-back beach town popular with surfers and travelers. The Masaya Volcano National Park, with an active lava lake, provides an up-close view of volcanic activity. Nicaraguan culture is a blend of Indigenous, Spanish, and African influences, and the country celebrates its cultural diversity through festivals, music, and dance. Traditional music, especially marimba and folk songs, plays an important role in Nicaraguan life. The annual Palo de Mayo festival on the Caribbean coast showcases Afro-Caribbean music and dance. Nicaraguan cuisine is simple but flavorful, often featuring corn, rice, and beans. Gallo pinto, a dish of rice and beans, is a staple meal, usually served with eggs for breakfast. Other popular dishes include nacatamal (a large tamale filled with meat and vegetables) and vigorón (a dish with yuca, cabbage, and pork). Fresh tropical fruits are also common, and ron (rum) is a popular local spirit. With its breathtaking natural landscapes, vibrant cultural traditions, and welcoming people, Nicaragua offers an authentic and less-explored experience in Central America. It’s an ideal destination for eco-tourists, adventure travelers, and those looking to enjoy both colonial charm and natural beauty in a peaceful setting.",
            "image": "images/countries/Nicaragua.jpg"
        },

        "panama": {
            "name": "Panama",
            "description": "Panama is a vibrant Central American country known for its unique geography, diverse culture, and strategic importance as a global trade hub. Bordered by Costa Rica to the west, Colombia to the southeast, the Caribbean Sea to the north, and the Pacific Ocean to the south, Panama is most famous for the Panama Canal, which connects the Atlantic and Pacific Oceans and plays a critical role in international shipping and commerce. Panama City, the capital, is a dynamic, cosmopolitan city with a skyline of modern skyscrapers, historical colonial neighborhoods like Casco Viejo, and bustling markets. Casco Viejo, a UNESCO World Heritage Site, showcases Spanish colonial architecture, vibrant nightlife, and eclectic dining. The city also has a unique blend of Indigenous, African, and European cultures, evident in its art, music, and food. The Panama Canal is the country’s most iconic landmark, drawing visitors from around the world to witness the engineering marvel that revolutionized global trade. The Miraflores Locks, one of the best spots to observe the canal in action, features a visitor center with exhibits detailing the canal’s history and impact. Beyond the canal, Panama is known for its diverse natural beauty. The country is home to lush rainforests, pristine beaches, and rich marine ecosystems. In the highlands, Boquete is popular for its coffee plantations, hiking trails, and cool climate. Bocas del Toro, an archipelago in the Caribbean, is famous for its clear waters, coral reefs, and relaxed atmosphere, making it a top destination for snorkeling, diving, and beach relaxation. The San Blas Islands, managed by the Indigenous Guna people, offer visitors a chance to experience traditional culture and stunning white-sand beaches. Panamanian cuisine reflects the country’s multicultural influences, with dishes like sancocho (a chicken and vegetable soup), arroz con pollo (rice with chicken), and fresh seafood on the coasts. Tropical fruits and coconut are commonly used, especially in Caribbean-inspired dishes. Panama is a melting pot of cultures, languages, and traditions, symbolized by its motto, 'Pro Mundi Beneficio (For the Benefit of the World'). With its rich history, cultural diversity, and natural beauty, Panama offers a unique blend of urban sophistication, traditional customs, and ecological wonders, making it a captivating destination for travelers.",
            "image": "images/countries/Panama.jpg"
        },

        "paraguay": {
            "name": "Paraguay",
            "description": "Paraguay is a landlocked country in South America, bordered by Argentina, Brazil, and Bolivia. Known as the 'Heart of South America' due to its central location, Paraguay is a culturally rich nation with a unique blend of Indigenous and Spanish influences, as well as stunning natural landscapes that range from lush rainforests to vast plains. Asunción, the capital, is one of South America's oldest cities and a cultural hub, with historic buildings, colonial architecture, and vibrant markets. The capital’s waterfront, known as the Costanera, is a popular spot for locals and visitors to enjoy views of the Paraguay River. Other cities like Ciudad del Este, near the border with Brazil and Argentina, are known for bustling commerce and proximity to the famous Iguazu Falls. Paraguay has a diverse cultural heritage rooted in both Indigenous Guaraní and Spanish traditions. The Guaraní language is widely spoken alongside Spanish, making Paraguay one of the few truly bilingual countries in the world. The culture is reflected in Paraguayan folk music, particularly the harp and guitar performances, as well as traditional dances like the polka paraguaya. Festivals and local crafts, including Ñandutí lace and ceramics, showcase the country's artistic heritage. Paraguayan cuisine is hearty and flavorful, featuring dishes like sopa paraguaya (a cornbread similar to a thick cake), chipa (a cheesy, doughy bread), and asado (barbecue). Many dishes use corn, cassava, and fresh cheese, ingredients deeply tied to the country’s agricultural roots. Tereré, a cold, herbal infusion similar to mate but served chilled, is Paraguay’s national drink and an essential part of daily social life. The country's natural beauty is also notable. In the eastern region, forests and rivers create habitats for diverse wildlife, while the Gran Chaco region in the west is a vast, arid plain home to unique species and Indigenous communities. Paraguay's natural parks, like Cerro Corá and Ybycuí, offer opportunities for ecotourism, birdwatching, and exploring the country’s biodiversity. Despite being relatively off the beaten path for tourism, Paraguay’s warm people, deep traditions, and blend of Indigenous and colonial influences make it a fascinating destination for those looking to experience an authentic and less-explored side of South America.",
            "image": "images/countries/Paraguay.jpg"
        },

        "peru": {
            "name": "Peru",
            "description": "Peru is a culturally rich and geographically diverse country in western South America, bordered by Ecuador, Colombia, Brazil, Bolivia, Chile, and the Pacific Ocean. It’s best known as the heart of the ancient Inca Empire, with the world-famous ruins of Machu Picchu, a UNESCO World Heritage Site, perched high in the Andes mountains. This iconic site draws visitors from around the world and offers a glimpse into Peru’s ancient history and engineering marvels. Peru’s landscape varies greatly, from the Amazon rainforest in the east to the arid coastal deserts, and the Andes mountains that run down the center. This variety gives rise to a wide array of ecosystems, making Peru one of the most biodiverse countries in the world. The Amazon basin is home to unique wildlife and is a hotspot for ecotourism. Peruvian culture is a blend of Indigenous, Spanish, African, and Asian influences, and each region has its own distinct traditions. Lima, the capital, is known for its historic architecture, museums, and vibrant food scene. Peruvian cuisine has gained international fame for dishes like ceviche (fresh fish marinated in lime juice), lomo saltado, and a variety of potato and corn-based dishes. The cuisine reflects the country's agricultural heritage, which includes native foods like quinoa, potatoes, and a vast array of corn varieties.",
            "image": "images/countries/Peru.jpg"
        },

        "puerto rico": {
            "name": "Puerto Rico",
            "description": "Puerto Rico is a vibrant Caribbean island and an unincorporated territory of the United States, located east of the Dominican Republic and west of the Virgin Islands. Known for its rich history, lively culture, and stunning natural landscapes, Puerto Rico offers a unique blend of Caribbean and Latin American influences with American ties. San Juan, the capital, is famous for its colorful colonial buildings, historic forts like Castillo San Felipe del Morro, and its cobblestone streets in Old San Juan. The city has a lively nightlife, with salsa music and dancing playing a central role in Puerto Rican culture. The island’s music, including reggaetón and salsa, is widely influential, with famous artists like Daddy Yankee, Bad Bunny, and Ricky Martin hailing from Puerto Rico. Puerto Rico’s natural beauty is also a major draw. The island has beautiful beaches, like Flamenco Beach on Culebra and Playa Sucia in Cabo Rojo. El Yunque National Forest, the only tropical rainforest in the U.S. National Forest System, is home to waterfalls, lush vegetation, and diverse wildlife. The island also has bioluminescent bays, such as Mosquito Bay in Vieques, where the water glows at night due to microscopic organisms. Puerto Rican cuisine, known as cocina criolla, combines Spanish, African, and Indigenous Taíno influences. Popular dishes include mofongo (mashed plantains with garlic and pork), arroz con gandules (rice with pigeon peas), and lechón (roast pork). Tropical fruits and coffee are also essential to the island’s culinary scene. Puerto Rico celebrates many festivals throughout the year, from the San Sebastián Street Festival in January to colorful parades during Carnival season. Despite challenges, the people of Puerto Rico, known as Boricuas, are known for their resilience and pride in their heritage. With its warm climate, vibrant culture, diverse landscapes, and historic charm, Puerto Rico is a popular destination offering a rich mix of relaxation, adventure, and cultural exploration for visitors.",
            "image": "images/countries/Puerto-Rico.jpg"
        },

        "spain": {
            "name": "Spain",
            "description": "Spain, located on the Iberian Peninsula in southwestern Europe, is known for its rich history, diverse landscapes, and vibrant culture. It shares borders with Portugal, France, and Andorra, and is bordered by both the Atlantic Ocean and the Mediterranean Sea. Spain is a mix of bustling cities, historic villages, Mediterranean beaches, and mountain ranges, with regions that offer unique cultural identities and traditions. Madrid, the capital, is a lively city with world-famous art museums, like the Prado and the Reina Sofia, as well as grand architecture and vibrant plazas. Barcelona, in Catalonia, is equally famous, known for its unique blend of modernist architecture, including Antoni Gaudí’s Sagrada Familia, and its bustling beach culture. Other notable cities include Seville, known for flamenco and Moorish influences; Granada, with the Alhambra palace; and Valencia, home to futuristic architecture and the famous paella dish. Spain's cultural landscape reflects a blend of Roman, Moorish, and European influences. Each region has its own traditions, languages (such as Catalan, Basque, and Galician), and cuisine. Spanish food is globally celebrated, with dishes like tapas, gazpacho, jamón ibérico, and tortilla española. Spain is also known for its wines, particularly from regions like Rioja and Ribera del Duero, and for sangria, a popular summer drink. Festivals play a major role in Spanish life, with events like La Tomatina (a massive tomato fight), the Running of the Bulls in Pamplona, and Semana Santa (Holy Week) processions attracting visitors from around the world. Flamenco, a traditional art form involving dance, guitar, and passionate singing, is a celebrated part of Spanish culture, especially in the Andalusian region. With its warm climate, rich history, diverse traditions, and stunning landscapes, Spain offers a unique blend of modern and historic experiences, making it a top destination for travelers seeking art, adventure, relaxation, and a taste of Mediterranean life.",
            "image": "images/countries/Spain.jpg",
        },

        "uruguay": {
            "name": "Uruguay",
            "description": "Uruguay is a small but charming country in South America, bordered by Argentina, Brazil, and the Atlantic Ocean. Known for its laid-back lifestyle, progressive social policies, and beautiful beaches, Uruguay offers a blend of coastal beauty, rich culture, and a strong tradition of hospitality. Despite its size, Uruguay has a unique character that distinguishes it within the region. Montevideo, the capital, is a vibrant city with a mix of European architecture, green spaces, and a relaxed atmosphere. The city’s historic Old Town, known as Ciudad Vieja, features colonial buildings, markets, and cultural landmarks like the iconic Solís Theatre. The Rambla, a coastal promenade stretching along the Rio de la Plata, is a popular spot for locals to walk, bike, and enjoy sunsets. Uruguay’s coastline is famous for its beaches, particularly in Punta del Este, a glamorous resort town known for its luxury hotels, nightlife, and sandy shores. Other beach destinations, like José Ignacio and La Paloma, offer more relaxed, scenic coastal experiences, attracting both surfers and beachgoers. The country’s interior, with rolling plains and cattle ranches, reflects Uruguay’s agricultural roots and traditional gaucho (cowboy) culture. Uruguayan culture blends European and Latin American influences, and its people are known for their warm, friendly nature. Tango and candombe (a traditional Afro-Uruguayan rhythm) are both important musical traditions, and the country celebrates Carnaval with vibrant parades, drumming, and dance. Uruguay shares a deep appreciation for soccer, and its national team has a proud history, winning the first FIFA World Cup in 1930. Uruguayan cuisine is hearty and heavily influenced by European flavors. Asado (barbecue) is a cherished culinary tradition, and meat dishes are central to the diet. Chivito, a popular sandwich with steak, ham, cheese, and vegetables, is a must-try. Mate, a herbal tea shared socially, is also a significant part of daily life, reflecting the country’s close-knit, communal culture. Uruguay is often celebrated for its progressive stance on social issues and its high quality of life. With a blend of urban sophistication, beachside charm, and deep cultural traditions, Uruguay is a peaceful, welcoming country that appeals to travelers seeking a more relaxed and authentic South American experience.",
            "image": "images/countries/Uruguay.jpg"
        },

        "venezuela": {
            "name": "Venezuela",
            "description": "Venezuela is a vibrant country in northern South America, bordered by Colombia, Brazil, Guyana, and the Caribbean Sea. Known for its stunning natural diversity, Venezuela boasts everything from Caribbean beaches and tropical rainforests to the towering Andes mountains and vast plains, known as the llanos, where cowboys (or llaneros) work. One of Venezuela’s most famous natural attractions is Angel Falls, the world’s highest waterfall, located in Canaima National Park. This UNESCO World Heritage site showcases the beauty of Venezuela’s tepui mountains—table-top formations that are home to unique ecosystems and breathtaking landscapes. The Orinoco River, one of the longest rivers in South America, flows through the country, supporting diverse wildlife and rainforests. Venezuelan culture is a blend of Indigenous, African, and Spanish influences, with each region having its own traditions and customs. The capital, Caracas, is a bustling metropolis with a mix of modern architecture, colonial landmarks, and a lively arts scene. Traditional Venezuelan music includes joropo, a style accompanied by harp, maracas, and a cuatro guitar, especially popular in the plains regions. Venezuelan culture is a blend of Indigenous, African, and Spanish influences, with each region having its own traditions and customs. Its landscapes, from Caribbean beaches to mountain peaks and dense rainforests, make it a fascinating destination with a lot to offer adventurous travelers.",
            "image": "images/countries/Venezuela.jpg"
        },
    }

    country_data = countries.get(country_name.lower())

    if not country_data:
        return render(request, '404.html')

    return render(request, 'common/country_detail.html', {"country": country_data})
