# Generated by Django 5.1.3 on 2024-11-21 00:00

from django.db import migrations, models

import QuieroAprender.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=QuieroAprender.accounts.models.profile_photo_upload_to,
            ),
        ),
    ]
